### ISSUE TITLE
ConvertJTokenToXml task

### ISSUE THREAD

**Issue by jvuoti** [FrendsPlatform/Frends.Json#3]
There should be a task for converting a JToken to XML, so you can e.g. do XSL-transforms easily enough on the data.

Previously, there was the Frends.Common.Data.ConvertData.ConvertToXML task, that just called  `JsonConvert.DeserializeXmlNode(Input, XMLRootElementName).OuterXml`. That should be good enough for now, as well.

**Comment by nickeeex** [comment]
This should be implemented in the XML task
