### ISSUE TITLE
Converting XML to JSON

### ISSUE THREAD

**Issue by DigiaAleksandrPaukku** [FrendsPlatform/Frends.Json#9]
Is Frends.Common.Data.ConvertToJSON task available any more? How can I do this conversion using available set of standard Frends tasks?

**Comment by CommunityHiQAdmin** [comment]
Have you tried this https://github.com/FrendsPlatform/Frends.Json#jsonconvertxmlstringtojtoken

**Comment by DigiaAleksandrPaukku** [comment]
It works, thanks! But it's result is JToken, not JSON string. Further explicit conversion does the rest thing.

**Comment by berghall** [comment]
To get the string representation of a JToken, use the method .ToString()
